/**
 * @description       : 
 * @author            : Enquero
 * @group             : 
 * @last modified on  : 06-10-2020
 * @last modified by  : Enquero
 * Modifications Log 
 * Ver   Date         Author    Modification
 * 1.0   06-10-2020   Enquero   Initial Version
**/
public with sharing class GitTest {
    private void checkdeployement() {
        System.debug('deployed sussesfully');
    }
}
